FROM zigbee2mqtt/zigbee2mqtt-aarch64:1.18.1-2
COPY freepad_ext.js /app/node_modules/zigbee-herdsman-converters/freepad_ext.js
COPY devices.js /app/node_modules/zigbee-herdsman-converters/devices.js
COPY tuya.js /app/node_modules/zigbee-herdsman-converters/lib/tuya.js
COPY fromZigbee.js /app/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js
COPY toZigbee.js /app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js